### ISSUE TITLE
Gettting Error 429 when launching

### ISSUE THREAD

**Issue by theraineydaze** [Kozova1/Parsec-Integration-With-RetroPie#20]
Sorry for being a super noob but I'm just starting with Raspberry Pi and I'm trying to get Parsec working with Retropie's front end. I can launch parsec from the terminal no problem but when I select Parsec from the Retropie menu it asks for login credentials then immediately gives me 'Error 429' and suggests I go on the Parsec Discord but I didn't get any answers. 
Anyone know how I can auto login through the front end, I'm sure their are scripts to make it happen but that's above my knowledge right now. When I first set it up after I entered 'sudo bash setup.sh -nodrv' it didn't ask me for a server ID, it just waited for a new command, so I entered 'parsec' and then it asked for an email and password then it worked, but I was hoping to launch from Retropie so I can use a controller for the whole experience. Thanks for reading.

**Comment by xayhewalo** [comment]
Error 429 means that there are too many login attempts. Wait an hour and try again. If you type "Error ####"  into the Parsec support channel, where "####" is the error number, a bot will reply with a FAQ page link. If that doesn't work you can search the channel for the error number and it will likely come up.

I got this error for weeks and it turned out that Parsec doesn't like non-alphanumeric characters in it's passwords. After I changed my password to only have numbers and letters I stopped getting the 429 error. Don't ask me why.

Also, "setup.sh" has been changed so you don't need to type in your Server ID. Just follow the onscreen directions. You'll need a keyboard and mouse for the initial setup but should be able to use a controller anytime afterwards.

I'll create a pull request to fix this README.md error
